//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinException.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinException.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ch_id&quot;: &quot;01234567&quot;, &quot;ch_bez&quot;: &quot;Charge1&quot;, &quot;equip_id&quot;: 1111,&quot;fname&quot;: &quot;F 1&quot;, &quot;a_version&quot;: &quot;0000&quot;, &quot;start_t&quot;: &quot;26.03.2020 07:00:00&quot;},
        ///{&quot;ch_id&quot;: &quot;01234568&quot;, &quot;ch_bez&quot;: &quot;Charge2&quot;, &quot;equip_id&quot;: 2222,&quot;fname&quot;: &quot;F 1&quot;, &quot;a_version&quot;: &quot;0008&quot;, &quot;start_t&quot;: &quot;28.10.2020 23:04:38&quot;},
        ///{&quot;ch_id&quot;: &quot;01234569&quot;, &quot;ch_bez&quot;: &quot;Charge3&quot;,	&quot;equip_id&quot;: 3333, &quot;fname&quot;: &quot;L 10&quot;,	&quot;a_version&quot;: &quot;0004&quot;, &quot;start_t&quot;: &quot;08.11.2020 10:55:01&quot;},
        ///{&quot;ch_id&quot;: &quot;12345678&quot;, &quot;ch_bez&quot;: &quot;Charge4&quot;,	&quot;equip_id&quot;: 4444, &quot;fname&quot;: &quot;L 12&quot;,	&quot;a_version&quot;: &quot;0004&quot;, &quot;start_t&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
